version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: burstslot
      POSTGRES_USER: toan
      POSTGRES_PASSWORD: Tranhuytoan04@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/burstslot
      SPRING_DATASOURCE_USERNAME: toan
      SPRING_DATASOURCE_PASSWORD: Tranhuytoan04@
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
